name: satellites
channels:
  - conda-forge
  - defaults
dependencies:
- python=3.7
- pip
- rasterio
- pandas
- geopandas
- imageio
- shapely
- xarray
- netCDF4
- geoviews
- rasterstats
- earthengine-api
- pydrive
- sqlalchemy
- celery
- python-dotenv
- descartes
- docker-compose

- pip:
  - cartopy
